;;; -*- coding: utf-8; -*-
;; isar-unicode-tokens.el --- Tokens for Unicode Tokens package
;;
;; Copyright(C) 2008 David Aspinall / LFCS Edinburgh
;; Author:    David Aspinall <David.Aspinall@ed.ac.uk>
;;
;; This file is loaded by `proof-unicode-tokens.el'.
;;
;; It sets the variables defined at the top of unicode-tokens.el,
;; unicode-tokens-<foo> is set from isar-<foo>.  See the corresponding
;; variable for documentation.
;;

(require 'proof-unicode-tokens)

;;
;; Controls
;;

(defconst isar-control-region-format-regexp
  "\\(\\\\<\\^%s>\\)\\(.*\\)\\(\\\\<\\^%s>\\)")

(defconst isar-control-char-format-regexp 
  "\\(\\\\<\\^%s>\\)\\([^\\]\\|\\\\<[A-Za-z]+>\\)")

(defconst isar-control-characters
  '(("sub" sub) 
    ("isub" sub)
    ("sup" sup) 
    ("isup" sup)
    ("loc" loc)
    ("bold" bold) 
    ("italic" italic))) ; unofficial

(defconst isar-control-regions
  '(("bsub" "esub" sub)
    ("bsup" "esup" sup) 
    ; unofficial:
    ("bbold" "ebold" bold)
    ("bitalic" "eitalic" italic)
    ("bscript" "escript" script)
    ("bfrakt" "efrakt" frakt)
    ("bserif" "eserif" serif)))
    
(defconst isar-fontsymb-properties 
  '((sub      (display (raise -0.4)))
    (sup      (display (raise 0.4)))
    (loc      (face proof-declaration-name-face))
    (bold     (face (:weight bold)))
    (italic   (face (:slant italic)))
    (script   (face unicode-tokens-script-font-face))
    (frakt    (face unicode-tokens-fraktur-font-face))
    (serif    (face unicode-tokens-serif-font-face))))

;;
;; Symbols
;;

;(defconst isar-token-format "\\<%s>") ; not used if below set
;(defconst isar-token-variant-format-regexp 
;  "\\\\<\\(%s\\)\\([:][a-zA-Z0-9]+\\)?>") ; syntax change
(defconst isar-token-variant-format-regexp 
  "\\\\<\\(%s\\)\\([0-9]+\\)?>") ; unofficial, syntax change

(defcustom isar-token-symbol-map
  `(; token name, unicode character composition, optional fontsymbs
    ;; Bold numerals
    ("one" "1" bold)
    ("two" "2" bold)
    ("three" "3" bold)
    ("four" "4" bold)
    ("five" "5" bold)
    ("six" "6" bold)
    ("seven" "7" bold)
    ("eight" "8" bold)
    ("nine" "9" bold)
    ;; Mathcal 
    ("A" "A" script)
    ("B" "B" script)
    ("C" "C" script)
    ("D" "D" script)
    ("E" "E" script)
    ("F" "F" script)
    ("G" "G" script)
    ("H" "H" script)
    ("I" "I" script)
    ("J" "J" script)
    ("K" "K" script)
    ("L" "L" script)
    ("M" "M" script)
    ("N" "N" script)
    ("O" "O" script)
    ("P" "P" script)
    ("Q" "Q" script)
    ("R" "R" script)
    ("S" "S" script)
    ("T" "T" script)
    ("U" "U" script)
    ("V" "V" script)
    ("W" "W" script)
    ("X" "X" script)
    ("Y" "Y" script)
    ("Z" "Z" script)
    ;; Math roman
    ("a" "a" serif)
    ("b" "b" serif)
    ("c" "c" serif)
    ("d" "d" serif)
    ("e" "e" serif)
    ("f" "f" serif)
    ("g" "g" serif)
    ("h" "h" serif)
    ("i" "i" serif)
    ("j" "j" serif)
    ("k" "k" serif)
    ("l" "l" serif)
    ("m" "m" serif)
    ("n" "n" serif)
    ("o" "o" serif)
    ("p" "p" serif)
    ("q" "q" serif)
    ("r" "r" serif)
    ("s" "s" serif)
    ("t" "t" serif)
    ("u" "u" serif)
    ("v" "v" serif)
    ("w" "w" serif)
    ("x" "x" serif)
    ("y" "y" serif)
    ("z" "z" serif)
    ;; Fraktur
    ("AA" "A" frakt)
    ("BB" "B" frakt)
    ("CC" "C" frakt)
    ("DD" "D" frakt)
    ("EE" "E" frakt)
    ("FF" "F" frakt)
    ("GG" "G" frakt)
    ("HH" "H" frakt)
    ("II" "I" frakt)
    ("JJ" "J" frakt)
    ("KK" "K" frakt)
    ("LL" "L" frakt)
    ("MM" "M" frakt)
    ("NN" "N" frakt)
    ("OO" "O" frakt)
    ("PP" "P" frakt)
    ("QQ" "Q" frakt)
    ("RR" "R" frakt)
    ("SS" "S" frakt)
    ("TT" "T" frakt)
    ("UU" "U" frakt)
    ("VV" "V" frakt)
    ("WW" "W" frakt)
    ("XX" "X" frakt)
    ("YY" "Y" frakt)
    ("ZZ" "Z" frakt)
    ("aa" "a" frakt)
    ("bb" "b" frakt)
    ("cc" "c" frakt)
    ("dd" "d" frakt)
    ("ee" "e" frakt)
    ("ff" "f" frakt)
    ("gg" "g" frakt)
    ("hh" "h" frakt)
    ("ii" "i" frakt)
    ("jj" "j" frakt)
    ("kk" "k" frakt)
    ("ll" "l" frakt)
    ("mm" "m" frakt)
    ("nn" "n" frakt)
    ("oo" "o" frakt)
    ("pp" "p" frakt)
    ("qq" "q" frakt)
    ("rr" "r" frakt)
    ("ss" "s" frakt)
    ("tt" "t" frakt)
    ("uu" "u" frakt)
    ("vv" "v" frakt)
    ("ww" "w" frakt)
    ("xx" "x" frakt)
    ("yy" "y" frakt)
    ("zz" "z" frakt)
    ("alpha" "α")
    ("beta" "β")
    ("gamma" "γ")
    ("delta" "δ")
    ("epsilon" "ε") ; actually varepsilon (some is epsilon)
    ("zeta" "ζ")
    ("eta" "η")
    ("theta" "θ")
    ("iota" "ι")
    ("kappa" "κ")
    ("lambda" "λ")
    ("mu" "μ")
    ("nu" "ν")
    ("xi" "ξ")
    ("pi" "π")
    ("rho" "ρ")
    ("sigma" "σ")
    ("tau" "τ")
    ("upsilon" "υ")
    ("phi" "ϕ")
    ("chi" "χ")
    ("psi" "ψ")
    ("omega" "ω")
    ("Gamma" "Γ")
    ("Delta" "Δ")
    ("Theta" "Θ")
    ("Lambda" "Λ")
    ("Xi" "Ξ")
    ("Pi" "Π")
    ("Sigma" "Σ")
    ("Upsilon" "Υ")
    ("Phi" "Φ")
    ("Psi" "Ψ")
    ("Omega" "Ω")
;;  ("bool" "")
    ("complex" "ℂ")
    ("nat" "ℕ")
    ("rat" "ℚ")
    ("real" "ℝ")
    ("int" "ℤ")
    ;; Arrows
    ("leftarrow" "←")
    ("rightarrow" "→")
    ("Leftarrow" "⇐")
    ("Rightarrow" "⇒")
    ("leftrightarrow" "↔")
    ("Leftrightarrow" "⇔")
    ("mapsto" "↦")
    ;; Real long symbols, may work in some places
    ("longleftarrow" "⟵")
    ("Longleftarrow" "⟸")
    ("longrightarrow" "⟶")
    ("Longrightarrow" "⟹")
    ("longleftrightarrow" "⟷")
    ("Longleftrightarrow" "⟺")
    ("longmapsto" "⟼")
    ;; Faked long symbols, for use otherwise:
;;;     ("longleftarrow" "←–")
;;;     ("Longleftarrow" "⇐–")
;;;     ("longrightarrow" "–→")
;;;     ("Longrightarrow" "–⇒")
;;;     ("longleftrightarrow" "←→")
;;;     ("Longleftrightarrow" "⇐⇒")
;;;     ("longmapsto" "❘→")
    ("midarrow" "–") ; #x002013 en dash
    ("Midarrow" "‗") ; #x002017 double low line (not mid)
    ("hookleftarrow" "↩")
    ("hookrightarrow" "↪")
    ("leftharpoondown" "↽")
    ("rightharpoondown" "⇁")
    ("leftharpoonup" "↼")
    ("rightharpoonup" "⇀")
    ("rightleftharpoons" "⇌")
    ("leadsto" "↝")
    ("downharpoonleft" "⇃")
    ("downharpoonright" "⇂")
    ("upharpoonleft" "↿")
    ;; ("upharpoonright" "↾") overlaps restriction
    ("restriction" "↾") ;; 
    ("Colon" "∷")
    ("up" "↑")
    ("Up" "⇑")
    ("down" "↓")
    ("Down" "⇓")
    ("updown" "↕")
    ("Updown" "⇕")
    ("langle" "⟪")
    ("rangle" "⟫")
    ("lceil" "⌈")
    ("rceil" "⌉")
    ("lfloor" "⌊")
    ("rfloor" "⌋")
    ("lparr" "⦇")
    ("rparr" "⦈")
    ("lbrakk" "⟦")
    ("rbrakk" "⟧")
;;     ("lbrace" "") TODO
;;    ("rbrace" "")
    ("guillemotleft" "«")
    ("guillemotright" "»")
    ("bottom" "⊥")
    ("top" "⊤")
    ("and" "∧")
    ("And" "⋀")
    ("or" "∨")
    ("Or" "⋁")
    ("forall" "∀")
    ("exists" "∃")
    ("nexists" "∄")
    ("not" "¬")
    ("box" "□")
    ("diamond" "◇")
    ("turnstile" "⊢")
    ("Turnstile" "⊨")
    ("tturnstile" "⊩")
    ("TTurnstile" "⊫")
    ("stileturn" "⊣")
    ("surd" "√")
    ("le" "≤")
    ("ge" "≥")
    ("lless" "≪")
    ("ggreater" "≫")
    ("lesssim" "⪍")
    ("greatersim" "⪎")
    ("lessapprox" "⪅")
    ("greaterapprox" "⪆")
    ("in" "∈")
    ("notin" "∉")
    ("subset" "⊂")
    ("supset" "⊃")
    ("subseteq" "⊆")
    ("supseteq" "⊇")    
    ("sqsubset" "⊏")
    ("sqsupset" "⊐")
    ("sqsubseteq" "⊑")
    ("sqsupseteq" "⊒")
    ("inter" "∩")
    ("Inter" "⋂")
    ("union" "∪")
    ("Union" "⋃")
    ("squnion" "⊔")
    ("Squnion" "⨆")
    ("sqinter" "⊓")
    ("Sqinter" "⨅")
    ("setminus" "∖")
    ("propto" "∝")
    ("uplus" "⊎")
    ("Uplus" "⨄")
    ("noteq" "≠")
    ("sim" "∼")
    ("doteq" "≐")
    ("simeq" "≃")
    ("approx" "≈")
    ("asymp" "≍")
    ("cong" "≅")
    ("smile" "⌣")
    ("equiv" "≡")
    ("frown" "⌢")
    ("Join" "⨝")
    ("bowtie" "⋈")
    ("prec" "≺")
    ("succ" "≻")
    ("preceq" "≼")
    ("succeq" "≽")
    ("parallel" "∥")
    ("bar" "¦")
    ("plusminus" "±")
    ("minusplus" "∓")
    ("times" "×")
    ("div" "÷")
    ("cdot" "⋅")
    ("star" "⋆")
    ("bullet" "∙")
    ("circ" "∘")
    ("dagger" "†")
    ("ddagger" "‡")
    ("lhd" "⊲")
    ("rhd" "⊳")
    ("unlhd" "⊴")
    ("unrhd" "⊵")
    ("triangleleft" "◁")
    ("triangleright" "▷")
    ("triangle" "▵") ; or △
    ("triangleq" "≜")
    ("oplus" "⊕")
    ("Oplus" "⨁")
    ("otimes" "⊗")
    ("Otimes" "⨂")
    ("odot" "⊙")
    ("Odot" "⨀")
    ("ominus" "⊖")
    ("oslash" "⊘") 
    ("dots" "…")
    ("cdots" "⋯")
    ("Sum" "∑")
    ("Prod" "∏")
    ("Coprod" "∐")
    ("infinity" "∞")
    ("integral" "∫")
    ("ointegral" "∮")
    ("clubsuit" "♣")
    ("diamondsuit" "♢")
    ("heartsuit" "♡")
    ("spadesuit" "♠")
    ("aleph" "ℵ")
    ("emptyset" "∅")
    ("nabla" "∇")
    ("partial" "∂")
    ("Re" "ℜ")
    ("Im" "ℑ")
    ("flat" "♭")
    ("natural" "♮")
    ("sharp" "♯")
    ("angle" "∠")
    ("copyright" "©")
    ("registered" "®")
    ("hyphen" "‐")
    ("inverse" "¯¹") ; X-Symb: just "¯"
    ("onesuperior" "¹")
    ("twosuperior" "²")
    ("threesuperior" "³")
    ("onequarter" "¼")
    ("onehalf" "½")
    ("threequarters" "¾")
    ("ordmasculine" "º")
    ("ordfeminine" "ª")
    ("section" "§")
    ("paragraph" "¶")
    ("exclamdown" "¡")
    ("questiondown" "¿")
    ("euro" "€")
    ("pounds" "£")
    ("yen" "¥")
    ("cent" "¢")
    ("currency" "¤")
    ("degree" "°")
    ("amalg" "⨿")
    ("mho" "℧")
    ("lozenge" "◊")
    ("wp" "℘")
    ("wrong" "≀") ;; #x002307
;;    ("struct" "") ;; TODO
    ("acute" "´")
    ("index" "ı")
    ("dieresis" "¨")
    ("cedilla" "¸")
    ("hungarumlaut" "ʺ")
    ("spacespace" "⁣⁣") ;; two #x002063
;    ("module" "") ??
    ("some" "ϵ")
    
    ;; Not in Standard Isabelle Symbols
    ;; (some are in X-Symbols)

    ("stareq" "≛")
    ("defeq" "≝")
    ("questioneq" "≟")
    ("vartheta" "ϑ")
    ; ("o" "ø")
    ("varpi" "ϖ")
    ("varrho" "ϱ")
    ("varsigma" "ς")
    ("varphi" "φ")
    ("hbar" "ℏ")
    ("ell" "ℓ")
    ("ast" "∗")

    ("bigcirc" "◯")
    ("bigtriangleup" "△")
    ("bigtriangledown" "▽")
    ("ni" "∋")
    ("mid" "∣")
    ("notlt" "≮")
    ("notle" "≰")
    ("notprec" "⊀")
    ("notpreceq" "⋠")
    ("notsubset" "⊄")
    ("notsubseteq" "⊈")
    ("notsqsubseteq" "⋢")
    ("notgt" "≯")
    ("notge" "≱")
    ("notsucc" "⊁")
    ("notsucceq" "⋡")
    ("notsupset" "⊅")
    ("notsupseteq" "⊉")
    ("notsqsupseteq" "⋣")
    ("notequiv" "≢")
    ("notsim" "≁")
    ("notsimeq" "≄")
    ("notapprox" "≉")
    ("notcong" "≇")
    ("notasymp" "≭")
    ("nearrow" "↗")
    ("searrow" "↘")
    ("swarrow" "↙")
    ("nwarrow" "↖")
    ("vdots" "⋮")
    ("ddots" "⋱")
    ("closequote" "’")
    ("openquote" "‘")
    ("opendblquote" "”")
    ("closedblquote" "“")
    ("emdash" "—")
    ("prime" "′")
    ("doubleprime" "″")
    ("tripleprime" "‴")
    ("quadrupleprime" "⁗")
    ("nbspace" " ")
    ("thinspace" " ")
    ("notni" "∌")
    ("colonequals" "≔")
    ("foursuperior" "⁴")
    ("fivesuperior" "⁵")
    ("sixsuperior" "⁶")
    ("sevensuperior" "⁷")
    ("eightsuperior" "⁸")
    ("ninesuperior" "⁹"))
  "Table mapping Isabelle symbol token names to Unicode strings.

You can adjust this table to add more entries, or to change entries for
glyphs that not are available in your Emacs or chosen font.

The token TNAME is made into the token \\< TNAME >.
The string mapping can be anything, but should be such that
tokens can be uniquely recovered from a decoded text; otherwise
results will be undefined when files are saved."
  :type '(repeat (cons (string :tag "Token name")
		       (string :tag "Unicode string")))
  :set 'proof-set-value
  :group 'isabelle
  :tag "Isabelle Unicode Token Mapping")


(defcustom isar-shortcut-alist
  '(; short cut, unicode string
;    ("<>" . "⋄")
;    ("|>" . "⊳")
    ("\\/" . "∨")
    ("/\\" . "∧")
    ("+O" . "⊕")
    ("-O" . "⊖")
    ("xO" . "⊗")
    ("/O" . "⊘")
    (".O" . "⊙")
    ("|+" . "†")
    ("|++" . "‡")
    ("<=" . "≤")
    ("|-" . "⊢")
    (">=" . "≥")
    ("-|" . "⊣")
    ("||" . "∥")
    ("==" . "≡")
    ("~=" . "≠")
    ("~:" . "∉")
;    ("~=" . "≃")
    ("~~~" . "≍")
    ("~~" . "≈")
    ("~==" . "≅")
    ("|<>|" . "⋈")
    ("|=" . "⊨")
    ("=." . "≐")
    ("_|_" . "⊥")
    ("</" . "≮")
    (">=/" . "≱")
    ("=/" . "≠")
    ("==/" . "≢")
    ("~/" . "≁")
    ("~=/" . "≄")
    ("~~/" . "≉")
    ("~==/" . "≇")
    ("<-" . "←")
;    ("<=" . "⇐")
    ("->" . "→")
    ("=>" . "⇒")
    ("<->" . "↔")
    ("<=>" . "⇔")
    ("|->" . "↦") 
    ("<--" . "⟵")
    ("<==" . "⟸")
    ("-->" . "⟶")
    ("==>" . "⟹")
    ("<==>" . "⟷")
    ("|-->" . "⟼")
    ("<-->" . "⟷")
    ("<<" . "«")
    ("[|" . "⟦")
    (">>" . "»")
    ("|]" . "⟧")
;    ("``" . "”")
;    ("''" . "“")
;    ("--" . "–")
    ("---" . "—")
;    ("''" . "″")
;    ("'''" . "‴")
;    ("''''" . "⁗")
;    (":=" . "≔")
    ;; some word shortcuts, started with backslash otherwise
    ;; too annoying.
    ("\\nat" . "ℕ")
    ("\\int" . "ℤ")
    ("\\rat" . "ℚ")
    ("\\real" . "ℝ")
    ("\\complex" . "ℂ")
    ("\\euro" . "€")
    ("\\yen" . "¥")
    ("\\cent" . "¢"))
  "Shortcut key sequence table for Unicode strings.

You can adjust this table to add more entries, or to change entries for
glyphs that not are available in your Emacs or chosen font.

These shortcuts are only used for input; no reverse conversion is
performed.  But if tokens exist for the target of shortcuts, they
will be used on saving the buffer."
  :type '(repeat (cons (string :tag "Shortcut sequence")
		       (string :tag "Unicode string")))
  :set 'proof-set-value
  :group 'isabelle
  :tag "Isabelle Unicode Token Mapping")

  


;;
;; prover symbol support 
;;

(eval-after-load "isar" 
  '(setq 
    proof-xsym-activate-command
    (isar-markup-ml "change print_mode (insert (op =) \"xsymbols\")")
    proof-xsym-deactivate-command
    (isar-markup-ml "change print_mode (remove (op =) \"xsymbols\")")))



(provide 'isar-unicode-tokens)

;;; isar-unicode-tokens.el ends here
